dist: xenial
sudo: required

language: cpp

git:
  depth: false

if: |
  branch IN (staging, trying, master)
  OR type = pull_request

addons:
  snaps:
  - &lxd lxd
  - &snapcraft
    name: snapcraft
    classic: true

env:
  global:
  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0

install:
- sudo apt remove --purge --assume-yes lxd lxd-client
- sudo /snap/bin/lxd waitready
- sudo /snap/bin/lxd init --auto
- sudo adduser $USER lxd
- ccache --max-size=5G

before_script:
# patch build system for the build type being processed
- "[ ! -f tests/travis.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis.patch"
- "[ ! -f tests/travis-${BUILD_TYPE}.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis-${BUILD_TYPE}.patch"

# set up ccache
- sg lxd -c '/snap/bin/lxc profile set default environment.PATH "/usr/lib/ccache:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
- sg lxd -c '/snap/bin/lxc profile device add default ccache disk source=${HOME}/.ccache/ path=/root/.ccache'
- ccache --zero-stats

after_failure:
- cat /tmp/*/trace.txt

after_success:
- ccache --show-stats

cache: ccache

jobs:
  include:
    - addons:
        snaps:
        - *lxd
        - *snapcraft
        - review-tools
      env: BUILD_TYPE=RelWithDebInfo
      script:
      - sg lxd -c '/snap/bin/snapcraft --use-lxd'
      - /snap/bin/review-tools.snap-review --allow-classic *.snap

    - env: BUILD_TYPE=Debug
      script:
      - sg lxd -c '/snap/bin/snapcraft build --use-lxd multipass'
      - sg lxd -c '/snap/bin/lxc start snapcraft-multipass'
      - sg lxd -c
          '/snap/bin/lxc exec snapcraft-multipass --
             env CTEST_OUTPUT_ON_FAILURE=1
                 LD_LIBRARY_PATH=/root/stage/usr/lib/x86_64-linux-gnu/:/root/stage/lib/
                 /root/parts/multipass/build/bin/multipass_tests'

    - env: BUILD_TYPE=Coverage
      script:
      - mkdir "${HOME}/parts"
      - sg lxd -c '/snap/bin/lxc profile device add default build disk source=${HOME}/parts path=/root/parts'
      - sg lxd -c '/snap/bin/snapcraft build --use-lxd multipass'
      - sg lxd -c '/snap/bin/lxc start snapcraft-multipass'
      - sg lxd -c
          '/snap/bin/lxc exec snapcraft-multipass --
             env CTEST_OUTPUT_ON_FAILURE=1
                 LD_LIBRARY_PATH=/root/stage/usr/lib/x86_64-linux-gnu/:/root/stage/lib/
                 cmake --build /root/parts/multipass/build --target covreport'
      after_success:
      - bash <(curl -s https://codecov.io/bash) -Z -s ${HOME/parts}
    - if: |
        repo = CanonicalLtd/multipass
               AND (type != pull_request
                    OR head_repo = repo)
      env: BUILD_TYPE=macOS
      git:
        submodules: false
      sudo: false
      addons: ~
      before_install:
      - openssl aes-256-cbc -K $encrypted_8d49841daf21_key -iv $encrypted_8d49841daf21_iv
        -in tools/bot-data.tar.xz.enc -out tools/bot-data.tar.xz -d
      - tar --extract --xz --file tools/bot-data.tar.xz --directory ${HOME}
      install: ~
      before_script: ~
      script:
      - |
        if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
          REF="+refs/pull/${TRAVIS_PULL_REQUEST}/merge"
        else
          REF="${TRAVIS_COMMIT}"
        fi
        ssh -q -p ${MAC_PORT} ${MAC_USERHOST} multipass-build/build-in-snapshot.sh "${REF}"
      after_success: ~
      after_failure: ~
      cache: ~
