os: linux
dist: bionic
language: cpp

git:
  submodules: false

stages:
- name: process snaps
  if: type = cron

jobs:
  include:
    - stage: process snaps
      name: Process snaps
      env: ~
      language: python
      python: 3.8

      addons:
        snaps:
        - review-tools

      before_install:
      - *decrypt-bot-data

      install:
      - *python-requirements

      script:
      - tools/process_snaps.py
