status = [ "Linux", "CI (Linux, lxd)", "CI (Linux, qemu)", "macOS", "CI (macOS, hyperkit)", "Windows", "CI (Windows, hyperv)" ]
block-labels = [ "no-merge" ]
timeout-sec = 12000
delete-merged-branches = true
update_base_for_deletes = true
cut_body_after = "---"
