blank_issues_enabled: true
contact_links:
  - name: Forums
    url: https://discourse.ubuntu.com/c/multipass
    about: Please ask and answer questions here.
  - name: "#multipass on Freenode"
    url: https://webchat.freenode.net/?channels=#multipass
    about: Chat to us!
