name: Lint
description: Run Linting steps

runs:
  using: composite
  steps:
  - name: Install clang-format
    shell: bash
    run: sudo apt-get install --no-install-recommends --yes clang-format-12

  - name: Run clang-format through the diff
    shell: bash
    run: |
      set -e -o pipefail

      # On pull requests, HEAD^1 will always be the merge base, so consider that diff for formatting.
      git diff -U0 --no-color HEAD^1 | clang-format-diff-12 -p1 | tee ${HOME}/clang-diff
      if [ "$( stat --printf='%s' ${HOME}/clang-diff )" -ne 0 ]; then
        echo "##[error] Please apply the above diff to correct formatting"
        exit 1
      fi
