name: multipass
version: 'git'
version-script: |
  git describe
summary: Ubuntu at your fingertips
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch`
  and it'll do all the setup for you. Check out `multipass find` for a list
  of available images. More details you can find under `multipass help`.

grade: devel
confinement: classic

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
    daemon: simple
  multipass:
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
    command: bin/multipass
    completer: etc/bash_completion.d/snap.multipass
  libvirt-bin:
    command: bin/launch-libvirtd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib:$SNAP/usr/lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: simple
  virsh:
    command: bin/virsh
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C

parts:
  qtbase5-dev:
    after: [qt5-qmake-bin]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/c856d6ab1b8a63760c60828108425c5b2dadb5de844ad0d77e12a77b5e47cf83
    prime: [-*]

  qtbase5-dev-tools:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev-tools_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/a4d6b840380a6aeff930947934c5d3f2dfc2a854346a0557e73f0fb862750402
    prime: [-*]

  qt5-qmake:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/b3f102f45ce7ef894f81133f10f33401b4430a7227ccc49c794dc7a0f637a76c
    prime: [-*]

  qt5-qmake-bin:
    after: [qt5-qmake]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake-bin_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/aae95892d51d92abd092211ffc473e0a85fecdc810a5ef058346557624979847
    prime: [-*]

  libqt5core5a:
    after: [libicu]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/27d43c6baab9555e77f76ce8faa637dbb9d3da9c7eb87cb44aaa63db3c79a519
    stage-packages:
    - libdouble-conversion1v5
    - libpcre16-3

  libqt5dbus5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5dbus5_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/0116e50f3db3aa2a9fe369347f649ea49969e6413611caa9ffbc670b5dffeb80

  libqt5network5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5network5_5.9.5+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/9ce96a38ede0d062071262ecc4a700b98f5e26f7054b8e351a0f0ca5bc8ca5f0
    stage-packages:
    - libproxy1v5

  libicu:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3_amd64.deb
    source-type: deb
    source-checksum: sha256/7a2f29ea19f2a14007fd84f25eb88db4fb3ca43bdb07fdb681329d2b5daca500

  multipass:
    after:
    - qtbase5-dev
    - qtbase5-dev-tools
    - libqt5core5a
    - libqt5network5
    - libvirt
    plugin: cmake
    build-packages:
    - build-essential
    - cmake-extras
    - golang
    - libsystemd-dev
    source: .
    configflags:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    override-build: |
      snapcraftctl build
      set -e
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass

  qemu:
    plugin: nil
    stage-packages:
    - qemu-system-x86
    - qemu-utils
    - libslang2
    organize:
      usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so: usr/lib/x86_64-linux-gnu/libpulsecommon-8.0.so
      usr/share/seabios/bios-256k.bin: qemu/bios-256k.bin
      usr/share/seabios/vgabios-stdvga.bin: qemu/vgabios-stdvga.bin
      usr/share/seabios/kvmvapic.bin: qemu/kvmvapic.bin
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/efi-virtio.rom

  kvm-support:
    plugin: nil
    stage-packages:
    - msr-tools

  libvirt:
    source: .
    source-subdir: libvirt-1.3.1
    plugin: autotools
    build-packages:
    - libxml2-dev
    - libxml-libxml-perl
    - libcurl4-gnutls-dev
    - libncurses5-dev
    - libreadline-dev
    - zlib1g-dev
    - libgcrypt20-dev
    - libgnutls28-dev
    - libyajl-dev
    - libpcap0.8-dev
    - libaudit-dev
    - libdevmapper-dev
    - libpciaccess-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - uuid-dev
    - libnuma-dev
    - python-all
    - python-six
    - wget
    - dpkg-dev
    stage-packages:
    - dmidecode
    - dnsmasq
    - libxml2
    - libyajl2
    - libnuma1
    - libcurl3-gnutls
    - libpciaccess0
    configflags:
    - --with-qemu
    - --without-bhyve
    - --without-xen
    - --without-openvz
    - --without-vmware
    - --without-xenapi
    - --without-esx
    - --without-hyperv
    - --without-lxc
    - --without-vz
    - --without-vbox
    - --without-uml
    - --without-sasl
    - --without-storage-iscsi
    - --without-storage-sheepdog
    - --without-storage-rbd
    - --without-storage-lvm
    - --without-selinux
    - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current
    - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - DNSMASQ=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dnsmasq
    - DMIDECODE=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dmidecode
    override-build: |
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1.orig.tar.gz
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.21.debian.tar.xz
      wget http://archive.ubuntu.com/ubuntu/pool/main/libv/libvirt/libvirt_1.3.1-1ubuntu10.21.dsc
      dpkg-source -x libvirt_1.3.1-1ubuntu10.21.dsc
      snapcraftctl build
    organize:
      # Hack to shift installed libvirt back to root of snap
      # required to ensure that pathing to files etc works at
      # runtime
      # * is not used to avoid directory merge conflicts
      snap/multipass/current/: ./

  network-utils:
    plugin: nil
    stage-packages:
    - iproute2
    - iputils-ping
    - libatm1

  glue:
    plugin: dump
    source: snap
