name: multipass
version: '2017.0.0'
version-script: |
  git describe
summary: Ubuntu at your fingertips
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch`
  and it'll do all the setup for you. Check out `multipass find` for a list
  of available images. More details you can find under `multipass help`.

grade: devel
confinement: classic

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu::$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
    daemon: simple
  multipass:
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu::$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
    command: bin/multipass
    completer: etc/bash_completion.d/snap.multipass

parts:
  qtbase5-dev:
    after: [qt5-qmake-bin]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/29364b97080c080696feb549b39d64c57d51360d0a27f6a3f2d956cfef063353
    prime: [-*]

  qtbase5-dev-tools:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev-tools_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/5a2dc0f0067bc3ba5f651fe22592601263cb6983059bf7540ea2a73c4ba592ef
    prime: [-*]

  qt5-qmake:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/4c37d7e8ec7dfa90a286033d3ac5f96fea061f96562960111ca4be1088530b7f
    prime: [-*]

  qt5-qmake-bin:
    after: [qt5-qmake]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake-bin_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/976120a7364332f9928e0f98fd051cc6389ef1bfbd185823e034d1f695e1ca00
    prime: [-*]

  libqt5core5a:
    after: [libicu]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/ebe9f9b7f0f9504d35dc7646938b5edf3e9ed05ba576f5fb9f5603f2b70fb213
    stage-packages:
    - libdouble-conversion1v5
    - libpcre16-3

  libqt5dbus5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5dbus5_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/34b99d2ef474bf17ed8f7adecc3cf58344366b50c847575fdcf6d4cd86dffc51

  libqt5network5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5network5_5.9.4+dfsg-0ubuntu4_amd64.deb
    source-type: deb
    source-checksum: sha256/7d15ac44f474a6fba61fa458f04cffba7db6047d2db32f87ec92eae4af5a656f
    stage-packages:
    - libproxy1v5

  libicu:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/3bd30b5935b2a91f10e532da52ffe4011695f69dc264e531a0a094fac284e89a

  multipass:
    after:
    - qtbase5-dev
    - qtbase5-dev-tools
    - libqt5core5a
    - libqt5network5
    plugin: cmake
    build-packages:
    - build-essential
    - cmake-extras
    - golang
    source: .
    configflags:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    install: |-
      set -ex
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass

  qemu:
    plugin: nil
    stage-packages:
    - qemu-system-x86
    - qemu-utils
    - libslang2
    organize:
      usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so: usr/lib/x86_64-linux-gnu/libpulsecommon-8.0.so
      usr/share/seabios/bios-256k.bin: qemu/bios-256k.bin
      usr/share/seabios/vgabios-stdvga.bin: qemu/vgabios-stdvga.bin
      usr/share/seabios/kvmvapic.bin: qemu/kvmvapic.bin
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/efi-virtio.rom

  dnsmasq:
    plugin: nil
    stage-packages:
    - dnsmasq

  kvm-support:
    plugin: nil
    stage-packages:
    - msr-tools

  network-utils:
    plugin: nil
    stage-packages:
    - iproute2
    - iputils-ping

  glue:
    plugin: dump
    source: snap
