#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths: &relevant-paths
      - "docs/**"
      - ".github/workflows/automatic-doc-checks.yml"
  merge_group:
    types: [checks_requested]
    paths: *relevant-paths
  workflow_dispatch:
    # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "./docs"
      fetch-depth: 0
