name: Test hooks
on:
  workflow_call:
  workflow_dispatch: # Manual trigger

jobs:
  TestHooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run hook tests
        run: |
          for hook in git-hooks/*.py; do
            echo "Testing $hook…"
            "$hook" --tests
          done
