name: TICS

on:
  workflow_dispatch:
  schedule:
  # 04:11 UTC every Sunday
  - cron: 11 4 * * 0

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted-linux-amd64-noble-large-tiobe

    env:
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      BUILD_DIR: ${{ github.workspace }}/build
      COVERAGE_DIR: ${{ github.workspace }}/coverage
      NEEDRESTART_SUSPEND: yes
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo --preserve-env apt-get install --yes \
          clang-tidy \
          devscripts \
          equivs \
          flake8 \
          lcov \
          ninja-build \
          pylint \
          python3-clang \
          python3-venv \
          python3-pip
        sudo --preserve-env apt-get build-dep --yes ./

    - name: Configure
      run: |
        cmake -B${{ env.BUILD_DIR }} \
              -DCMAKE_BUILD_TYPE=Coverage

    - name: Add Flutter to $PATH
      run: |
        echo "$GITHUB_WORKSPACE/3rd-party/flutter/bin" >> $GITHUB_PATH

    - name: Install Dart analysis tools
      run: |
        dart pub global activate cobertura

    - name: Install Flutter deps
      working-directory: src/client/gui
      run: flutter pub get

    - name: BuildAndTest
      run: |
        cmake --build ${{ env.BUILD_DIR }} \
              --target covreport \
              -j$(nproc)

    - name: Convert lcov to Cobertura XML
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install gcovr

        mkdir -p ${{ env.COVERAGE_DIR }}
        gcovr -r ${{ github.workspace }} \
              --object-directory ${{ env.BUILD_DIR }} \
              --cobertura ${{ env.COVERAGE_DIR }}/coverage.xml \
              --gcov-ignore-parse-errors

    - name: Run TICS Analysis
      uses: tiobe/tics-github-action@v3
      with:
        mode: qserver
        project: multipass
        viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
        ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
        installTics: true

    - name: Report workflow failure
      if: ${{ failure() || cancelled() }}
      uses: mattermost/action-mattermost-notify@master
      with:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: multipass
        TEXT: |
          :red_circle: @mp
          Scheduled [TICS](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) workflow exited before completing.
        MATTERMOST_USERNAME: ${{ github.triggering_actor }}
        MATTERMOST_ICON_URL: https://www.flaticon.com/free-icon/github-logo_25231
